[subsystem]
name = "test"
id = 0

[motors]
[motors.front_left]
type = "TalonFX"
id = 1
inverted = false
canbus = "canivore"
slot = 0 # Need better way than this, as will be hard to track between toml files
stator_current = 40
supply_current = 120

[motors.front_right]
type = "TalonFX"
id = 2
inverted = false
canbus = "canivore"
slot = 0
stator_current = 40
supply_current = 120

[sensors]
[sensors.front_left_encoder]
inverted = false
