[subsystem]
name = "test"
node = "//2026-robot/main_processor/test:node"
period_us = 5000

[motors.front_left]
type = "TalonFX"
bus = "canivore"
can_id = 1
inverted = false
supply_limit_a = 40
stator_limit_a = 80
slot0 = { p = 0.1, i = 0.0, d = 0.0, v = 0.12 }

[motors.front_right]
type = "TalonFX"
bus = "canivore"
can_id = 2
inverted = false
supply_limit_a = 40
stator_limit_a = 80
slot0 = { p = 0.1, i = 0.0, d = 0.0, v = 0.12 }

[sensors.front_left_encoder]
type = "CANcoder"
bus = "canivore"
can_id = 20
offset_rot = 0.0
