[subsystem]
name = "test"
id = 0

[motors]
[motors.front_left]
type = "TalonFX"
id = 2
inverted = false
canbus = "canivore"

[motors.front_right]
type = "TalonFX"
id = 2
inverted = false
canbus = "canivore"

[sensors]
[sensors.front_left_encoder]
nverted = false
