# automatically generated by the FlatBuffers compiler, do not modify

# namespace: intake

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IntakeState(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # IntakeState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntakeState
    def IssuedNs(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # IntakeState
    def Enabled(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # IntakeState
    def RollerVelocityRps(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # IntakeState
    def BeamBroken(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateIntakeState(builder, issuedNs, enabled, rollerVelocityRps, beamBroken):
    builder.Prep(8, 24)
    builder.Pad(7)
    builder.PrependBool(beamBroken)
    builder.PrependFloat32(rollerVelocityRps)
    builder.Pad(3)
    builder.PrependBool(enabled)
    builder.PrependUint64(issuedNs)
    return builder.Offset()
