# automatically generated by the FlatBuffers compiler, do not modify

# namespace: intake

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IntakeTarget(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # IntakeTarget
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IntakeTarget
    def IssuedNs(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # IntakeTarget
    def Enabled(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # IntakeTarget
    def RollerVelocityRps(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateIntakeTarget(builder, issuedNs, enabled, rollerVelocityRps):
    builder.Prep(8, 16)
    builder.PrependFloat32(rollerVelocityRps)
    builder.Pad(3)
    builder.PrependBool(enabled)
    builder.PrependUint64(issuedNs)
    return builder.Offset()
