load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "test1",
    size = "small",
    srcs = ["test.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
