# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPCMessage

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TestMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # TestMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TestMessage
    def Id(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # TestMessage
    def Value(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateTestMessage(builder, id, value):
    builder.Prep(4, 8)
    builder.PrependFloat32(value)
    builder.PrependInt32(id)
    return builder.Offset()
