# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPCMessage

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TimeMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 208

    # TimeMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TimeMessage
    def Id(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # TimeMessage
    def Value(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # TimeMessage
    def Padding(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16 + i * 1)) for i in range(self.PaddingLength())]
        elif j >= 0 and j < self.PaddingLength():
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16 + j * 1))
        else:
            return None

    # TimeMessage
    def PaddingAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Uint8Flags, self._tab.Pos + 16, self.PaddingLength())

    # TimeMessage
    def PaddingLength(self):
        return 192

    # TimeMessage
    def PaddingIsNone(self):
        return False


def CreateTimeMessage(builder, id, value, padding):
    builder.Prep(8, 208)
    for _idx0 in range(192 , 0, -1):
        builder.PrependUint8(padding[_idx0-1])
    builder.PrependUint64(value)
    builder.Pad(4)
    builder.PrependInt32(id)
    return builder.Offset()
