load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "flatbuffers_message",
    srcs = ["test.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ]
)
