load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_test(
    name = "rtms_test",
    size = "small",
    srcs = ["test.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ]
)

